# Streamlit Cloud Configuration
# This file is used by Streamlit Cloud for deployment

[general]
email = ""

[server]
headless = true
port = $PORT
enableCORS = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
